#!/bin/sh

MAC=$(cat /etc/board.json | jsonfilter -e '@["network"]["wan"]["macaddr"]' | tr -d :)
WAN=$(cat /etc/board.json | jsonfilter -e '@["network"]["wan"]["ifname"]' | tr -d :)
[ -n "$WAN" ] || WAN="eth0"
[ -n "$MAC" ] || MAC=$(cat /sys/class/net/$WAN/address | tr -d ":")
uci set system.@system[-1].hostname="OpenAp-${MAC:6}"
uci commit system

exit 0
